#!/usr/bin/env ruby

require 'sdl'

if ARGV.grep(/\-root/).size > 0 then          # A
  require 'vroot'
  ENV['SDL_WINDOWID'] = VRoot::windowid.to_s  # B
  src_w = VRoot::width
  src_h = VRoot::height
  src_d = VRoot::depth
else
  src_w = 640
  src_h = 480
  src_d = 16
end

dst_w = 0
dst_h = 0

RECTSIZE = src_w / 4

SDL.init(SDL::INIT_VIDEO)
$SCREEN = SDL::setVideoMode src_w,src_h,src_d,
      SDL::SWSURFACE|SDL::ANYFORMAT           # C
$SCREEN.fillRect 0,0,src_w,src_h,[255,0,0]
$SCREEN.flip

loop do
  while event = SDL::Event2.poll
    case event
    when SDL::Event2::Quit                    # D
      exit
    end
  end
  
  color = $SCREEN.mapRGB rand(256),rand(256),rand(256)
  dst_w = rand(RECTSIZE) + 1
  dst_h = rand(RECTSIZE) + 1
  $SCREEN.fillRect rand(src_w-dst_w), rand(src_h-dst_h), dst_w, dst_h, color
  $SCREEN.updateRect 0,0,0,0
end

